spring:
  profiles:
    active: dev
  messages:
    encoding: UTF-8

server:
  port: 8080

logging:
  level:
    root:  ERROR
    org.springframework:  ERROR
    org.mybatis:  ERROR
    com.hdyanfa.interact:  DEBUG
