package org.hdyanfa.demo.dao;

import org.apache.ibatis.annotations.Param;
import org.hdyanfa.demo.domain.ChatGroupToUser;
import org.hdyanfa.demo.domain.ChatGroupToUserExample;

import java.util.List;

public interface ChatGroupToUserMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table chat_group_to_user
     *
     * @mbg.generated
     */
    long countByExample(ChatGroupToUserExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table chat_group_to_user
     *
     * @mbg.generated
     */
    int deleteByExample(ChatGroupToUserExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table chat_group_to_user
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table chat_group_to_user
     *
     * @mbg.generated
     */
    int insert(ChatGroupToUser record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table chat_group_to_user
     *
     * @mbg.generated
     */
    int insertSelective(ChatGroupToUser record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table chat_group_to_user
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    ChatGroupToUser selectOneByExample(ChatGroupToUserExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table chat_group_to_user
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    ChatGroupToUser selectOneByExampleSelective(@Param("example") ChatGroupToUserExample example, @Param("selective") ChatGroupToUser.Column... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table chat_group_to_user
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    List<ChatGroupToUser> selectByExampleSelective(@Param("example") ChatGroupToUserExample example, @Param("selective") ChatGroupToUser.Column... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table chat_group_to_user
     *
     * @mbg.generated
     */
    List<ChatGroupToUser> selectByExample(ChatGroupToUserExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table chat_group_to_user
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    ChatGroupToUser selectByPrimaryKeySelective(@Param("id") Integer id, @Param("selective") ChatGroupToUser.Column... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table chat_group_to_user
     *
     * @mbg.generated
     */
    ChatGroupToUser selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table chat_group_to_user
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    ChatGroupToUser selectByPrimaryKeyWithLogicalDelete(@Param("id") Integer id, @Param("andLogicalDeleted") boolean andLogicalDeleted);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table chat_group_to_user
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") ChatGroupToUser record, @Param("example") ChatGroupToUserExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table chat_group_to_user
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") ChatGroupToUser record, @Param("example") ChatGroupToUserExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table chat_group_to_user
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(ChatGroupToUser record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table chat_group_to_user
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(ChatGroupToUser record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table chat_group_to_user
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    int logicalDeleteByExample(@Param("example") ChatGroupToUserExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table chat_group_to_user
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    int logicalDeleteByPrimaryKey(Integer id);
}