package org.hdyanfa.demo.domain;

import java.time.LocalDateTime;
import java.util.ArrayList;
import java.util.Arrays;

public class ChatGroupToUser {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table chat_group_to_user
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    public static final Boolean NOT_DELETED = false;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table chat_group_to_user
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    public static final Boolean IS_DELETED = true;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column chat_group_to_user.id
     *
     * @mbg.generated
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column chat_group_to_user.user_id
     *
     * @mbg.generated
     */
    private Integer userId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column chat_group_to_user.c_group_id
     *
     * @mbg.generated
     */
    private Integer cGroupId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column chat_group_to_user.nikename
     *
     * @mbg.generated
     */
    private String nikename;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column chat_group_to_user.is_top
     *
     * @mbg.generated
     */
    private Boolean isTop;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column chat_group_to_user.is_no_disturb
     *
     * @mbg.generated
     */
    private Boolean isNoDisturb;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column chat_group_to_user.bg_url
     *
     * @mbg.generated
     */
    private String bgUrl;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column chat_group_to_user.user_status
     *
     * @mbg.generated
     */
    private Integer userStatus;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column chat_group_to_user.validate_content
     *
     * @mbg.generated
     */
    private String validateContent;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column chat_group_to_user.add_time
     *
     * @mbg.generated
     */
    private LocalDateTime addTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column chat_group_to_user.update_time
     *
     * @mbg.generated
     */
    private LocalDateTime updateTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column chat_group_to_user.deleted
     *
     * @mbg.generated
     */
    private Boolean deleted;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column chat_group_to_user.id
     *
     * @return the value of chat_group_to_user.id
     *
     * @mbg.generated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column chat_group_to_user.id
     *
     * @param id the value for chat_group_to_user.id
     *
     * @mbg.generated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column chat_group_to_user.user_id
     *
     * @return the value of chat_group_to_user.user_id
     *
     * @mbg.generated
     */
    public Integer getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column chat_group_to_user.user_id
     *
     * @param userId the value for chat_group_to_user.user_id
     *
     * @mbg.generated
     */
    public void setUserId(Integer userId) {
        this.userId = userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column chat_group_to_user.c_group_id
     *
     * @return the value of chat_group_to_user.c_group_id
     *
     * @mbg.generated
     */
    public Integer getcGroupId() {
        return cGroupId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column chat_group_to_user.c_group_id
     *
     * @param cGroupId the value for chat_group_to_user.c_group_id
     *
     * @mbg.generated
     */
    public void setcGroupId(Integer cGroupId) {
        this.cGroupId = cGroupId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column chat_group_to_user.nikename
     *
     * @return the value of chat_group_to_user.nikename
     *
     * @mbg.generated
     */
    public String getNikename() {
        return nikename;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column chat_group_to_user.nikename
     *
     * @param nikename the value for chat_group_to_user.nikename
     *
     * @mbg.generated
     */
    public void setNikename(String nikename) {
        this.nikename = nikename;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column chat_group_to_user.is_top
     *
     * @return the value of chat_group_to_user.is_top
     *
     * @mbg.generated
     */
    public Boolean getIsTop() {
        return isTop;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column chat_group_to_user.is_top
     *
     * @param isTop the value for chat_group_to_user.is_top
     *
     * @mbg.generated
     */
    public void setIsTop(Boolean isTop) {
        this.isTop = isTop;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column chat_group_to_user.is_no_disturb
     *
     * @return the value of chat_group_to_user.is_no_disturb
     *
     * @mbg.generated
     */
    public Boolean getIsNoDisturb() {
        return isNoDisturb;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column chat_group_to_user.is_no_disturb
     *
     * @param isNoDisturb the value for chat_group_to_user.is_no_disturb
     *
     * @mbg.generated
     */
    public void setIsNoDisturb(Boolean isNoDisturb) {
        this.isNoDisturb = isNoDisturb;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column chat_group_to_user.bg_url
     *
     * @return the value of chat_group_to_user.bg_url
     *
     * @mbg.generated
     */
    public String getBgUrl() {
        return bgUrl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column chat_group_to_user.bg_url
     *
     * @param bgUrl the value for chat_group_to_user.bg_url
     *
     * @mbg.generated
     */
    public void setBgUrl(String bgUrl) {
        this.bgUrl = bgUrl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column chat_group_to_user.user_status
     *
     * @return the value of chat_group_to_user.user_status
     *
     * @mbg.generated
     */
    public Integer getUserStatus() {
        return userStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column chat_group_to_user.user_status
     *
     * @param userStatus the value for chat_group_to_user.user_status
     *
     * @mbg.generated
     */
    public void setUserStatus(Integer userStatus) {
        this.userStatus = userStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column chat_group_to_user.validate_content
     *
     * @return the value of chat_group_to_user.validate_content
     *
     * @mbg.generated
     */
    public String getValidateContent() {
        return validateContent;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column chat_group_to_user.validate_content
     *
     * @param validateContent the value for chat_group_to_user.validate_content
     *
     * @mbg.generated
     */
    public void setValidateContent(String validateContent) {
        this.validateContent = validateContent;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column chat_group_to_user.add_time
     *
     * @return the value of chat_group_to_user.add_time
     *
     * @mbg.generated
     */
    public LocalDateTime getAddTime() {
        return addTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column chat_group_to_user.add_time
     *
     * @param addTime the value for chat_group_to_user.add_time
     *
     * @mbg.generated
     */
    public void setAddTime(LocalDateTime addTime) {
        this.addTime = addTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column chat_group_to_user.update_time
     *
     * @return the value of chat_group_to_user.update_time
     *
     * @mbg.generated
     */
    public LocalDateTime getUpdateTime() {
        return updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column chat_group_to_user.update_time
     *
     * @param updateTime the value for chat_group_to_user.update_time
     *
     * @mbg.generated
     */
    public void setUpdateTime(LocalDateTime updateTime) {
        this.updateTime = updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column chat_group_to_user.deleted
     *
     * @return the value of chat_group_to_user.deleted
     *
     * @mbg.generated
     */
    public Boolean getDeleted() {
        return deleted;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column chat_group_to_user.deleted
     *
     * @param deleted the value for chat_group_to_user.deleted
     *
     * @mbg.generated
     */
    public void setDeleted(Boolean deleted) {
        this.deleted = deleted;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table chat_group_to_user
     *
     * @mbg.generated
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", id=").append(id);
        sb.append(", userId=").append(userId);
        sb.append(", cGroupId=").append(cGroupId);
        sb.append(", nikename=").append(nikename);
        sb.append(", isTop=").append(isTop);
        sb.append(", isNoDisturb=").append(isNoDisturb);
        sb.append(", bgUrl=").append(bgUrl);
        sb.append(", userStatus=").append(userStatus);
        sb.append(", validateContent=").append(validateContent);
        sb.append(", addTime=").append(addTime);
        sb.append(", updateTime=").append(updateTime);
        sb.append(", deleted=").append(deleted);
        sb.append("]");
        return sb.toString();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table chat_group_to_user
     *
     * @mbg.generated
     */
    @Override
    public boolean equals(Object that) {
        if (this == that) {
            return true;
        }
        if (that == null) {
            return false;
        }
        if (getClass() != that.getClass()) {
            return false;
        }
        ChatGroupToUser other = (ChatGroupToUser) that;
        return (this.getId() == null ? other.getId() == null : this.getId().equals(other.getId()))
            && (this.getUserId() == null ? other.getUserId() == null : this.getUserId().equals(other.getUserId()))
            && (this.getcGroupId() == null ? other.getcGroupId() == null : this.getcGroupId().equals(other.getcGroupId()))
            && (this.getNikename() == null ? other.getNikename() == null : this.getNikename().equals(other.getNikename()))
            && (this.getIsTop() == null ? other.getIsTop() == null : this.getIsTop().equals(other.getIsTop()))
            && (this.getIsNoDisturb() == null ? other.getIsNoDisturb() == null : this.getIsNoDisturb().equals(other.getIsNoDisturb()))
            && (this.getBgUrl() == null ? other.getBgUrl() == null : this.getBgUrl().equals(other.getBgUrl()))
            && (this.getUserStatus() == null ? other.getUserStatus() == null : this.getUserStatus().equals(other.getUserStatus()))
            && (this.getValidateContent() == null ? other.getValidateContent() == null : this.getValidateContent().equals(other.getValidateContent()))
            && (this.getAddTime() == null ? other.getAddTime() == null : this.getAddTime().equals(other.getAddTime()))
            && (this.getUpdateTime() == null ? other.getUpdateTime() == null : this.getUpdateTime().equals(other.getUpdateTime()))
            && (this.getDeleted() == null ? other.getDeleted() == null : this.getDeleted().equals(other.getDeleted()));
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table chat_group_to_user
     *
     * @mbg.generated
     */
    @Override
    public int hashCode() {
        final int prime = 31;
        int result = 1;
        result = prime * result + ((getId() == null) ? 0 : getId().hashCode());
        result = prime * result + ((getUserId() == null) ? 0 : getUserId().hashCode());
        result = prime * result + ((getcGroupId() == null) ? 0 : getcGroupId().hashCode());
        result = prime * result + ((getNikename() == null) ? 0 : getNikename().hashCode());
        result = prime * result + ((getIsTop() == null) ? 0 : getIsTop().hashCode());
        result = prime * result + ((getIsNoDisturb() == null) ? 0 : getIsNoDisturb().hashCode());
        result = prime * result + ((getBgUrl() == null) ? 0 : getBgUrl().hashCode());
        result = prime * result + ((getUserStatus() == null) ? 0 : getUserStatus().hashCode());
        result = prime * result + ((getValidateContent() == null) ? 0 : getValidateContent().hashCode());
        result = prime * result + ((getAddTime() == null) ? 0 : getAddTime().hashCode());
        result = prime * result + ((getUpdateTime() == null) ? 0 : getUpdateTime().hashCode());
        result = prime * result + ((getDeleted() == null) ? 0 : getDeleted().hashCode());
        return result;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table chat_group_to_user
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    public void andLogicalDeleted(boolean deleted) {
        setDeleted(deleted ? IS_DELETED : NOT_DELETED);
    }

    /**
     * This enum was generated by MyBatis Generator.
     * This enum corresponds to the database table chat_group_to_user
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    public enum Column {
        id("id", "id", "INTEGER", false),
        userId("user_id", "userId", "INTEGER", false),
        cGroupId("c_group_id", "cGroupId", "INTEGER", false),
        nikename("nikename", "nikename", "VARCHAR", false),
        isTop("is_top", "isTop", "BIT", false),
        isNoDisturb("is_no_disturb", "isNoDisturb", "BIT", false),
        bgUrl("bg_url", "bgUrl", "VARCHAR", false),
        userStatus("user_status", "userStatus", "INTEGER", false),
        validateContent("validate_content", "validateContent", "VARCHAR", false),
        addTime("add_time", "addTime", "TIMESTAMP", false),
        updateTime("update_time", "updateTime", "TIMESTAMP", false),
        deleted("deleted", "deleted", "BIT", false);

        /**
         * This field was generated by MyBatis Generator.
         * This field corresponds to the database table chat_group_to_user
         *
         * @mbg.generated
         * @project https://github.com/itfsw/mybatis-generator-plugin
         */
        private static final String BEGINNING_DELIMITER = "`";

        /**
         * This field was generated by MyBatis Generator.
         * This field corresponds to the database table chat_group_to_user
         *
         * @mbg.generated
         * @project https://github.com/itfsw/mybatis-generator-plugin
         */
        private static final String ENDING_DELIMITER = "`";

        /**
         * This field was generated by MyBatis Generator.
         * This field corresponds to the database table chat_group_to_user
         *
         * @mbg.generated
         * @project https://github.com/itfsw/mybatis-generator-plugin
         */
        private final String column;

        /**
         * This field was generated by MyBatis Generator.
         * This field corresponds to the database table chat_group_to_user
         *
         * @mbg.generated
         * @project https://github.com/itfsw/mybatis-generator-plugin
         */
        private final boolean isColumnNameDelimited;

        /**
         * This field was generated by MyBatis Generator.
         * This field corresponds to the database table chat_group_to_user
         *
         * @mbg.generated
         * @project https://github.com/itfsw/mybatis-generator-plugin
         */
        private final String javaProperty;

        /**
         * This field was generated by MyBatis Generator.
         * This field corresponds to the database table chat_group_to_user
         *
         * @mbg.generated
         * @project https://github.com/itfsw/mybatis-generator-plugin
         */
        private final String jdbcType;

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table chat_group_to_user
         *
         * @mbg.generated
         * @project https://github.com/itfsw/mybatis-generator-plugin
         */
        public String value() {
            return this.column;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table chat_group_to_user
         *
         * @mbg.generated
         * @project https://github.com/itfsw/mybatis-generator-plugin
         */
        public String getValue() {
            return this.column;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table chat_group_to_user
         *
         * @mbg.generated
         * @project https://github.com/itfsw/mybatis-generator-plugin
         */
        public String getJavaProperty() {
            return this.javaProperty;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table chat_group_to_user
         *
         * @mbg.generated
         * @project https://github.com/itfsw/mybatis-generator-plugin
         */
        public String getJdbcType() {
            return this.jdbcType;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table chat_group_to_user
         *
         * @mbg.generated
         * @project https://github.com/itfsw/mybatis-generator-plugin
         */
        Column(String column, String javaProperty, String jdbcType, boolean isColumnNameDelimited) {
            this.column = column;
            this.javaProperty = javaProperty;
            this.jdbcType = jdbcType;
            this.isColumnNameDelimited = isColumnNameDelimited;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table chat_group_to_user
         *
         * @mbg.generated
         * @project https://github.com/itfsw/mybatis-generator-plugin
         */
        public String desc() {
            return this.getEscapedColumnName() + " DESC";
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table chat_group_to_user
         *
         * @mbg.generated
         * @project https://github.com/itfsw/mybatis-generator-plugin
         */
        public String asc() {
            return this.getEscapedColumnName() + " ASC";
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table chat_group_to_user
         *
         * @mbg.generated
         * @project https://github.com/itfsw/mybatis-generator-plugin
         */
        public static Column[] excludes(Column ... excludes) {
            ArrayList<Column> columns = new ArrayList<>(Arrays.asList(Column.values()));
            if (excludes != null && excludes.length > 0) {
                columns.removeAll(new ArrayList<>(Arrays.asList(excludes)));
            }
            return columns.toArray(new Column[]{});
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table chat_group_to_user
         *
         * @mbg.generated
         * @project https://github.com/itfsw/mybatis-generator-plugin
         */
        public String getEscapedColumnName() {
            if (this.isColumnNameDelimited) {
                return new StringBuilder().append(BEGINNING_DELIMITER).append(this.column).append(ENDING_DELIMITER).toString();
            } else {
                return this.column;
            }
        }
    }
}